---
- name: add environment variable NO_PROXY
  lineinfile:
    line: '{{ item }}={{ no_proxy }}'
    path: /etc/environment
    regexp: '^\s*{{ item }}\s*='
  notify: reboot system
  when: proxy_url != "None"
  with_items:
    - no_proxy
- name: add environment variables HTTP_PROXY and HTTPS_PROXY
  lineinfile:
    line: '{{ item }}={{ proxy_url }}'
    path: /etc/environment
    regexp: '^\s*{{ item }}\s*='
  notify: reboot system
  when: proxy_url != "None"
  with_items:
    - http_proxy
    - https_proxy
- name: add apt proxies
  template:
    dest: /etc/apt/apt.conf.d/95proxies
    src: 95proxies.j2
  when: proxy_url != "None"
- name: update cache and upgrade dist
  apt:
    update_cache: yes
    upgrade: dist
  notify: reboot system
- name: install common apt packages
  apt:
    name:
      - apt-transport-https
      - avahi-daemon
      - ca-certificates
      - curl
      - net-tools
      - nfs-common
      - open-iscsi
      - software-properties-common
- name: remove obsolete or unused packages
  apt:
    autoclean: yes
    autoremove: yes
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  notify: reload avahi-daemon
- name: "set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  notify: restart cron
- name: "set locale to {{ locale }}"
  lineinfile:
    line: 'LANG={{ locale }}'
    path: /etc/default/locale
    regexp: '^\s*#?\s*LANG\s*='
  notify: reboot system
- meta: flush_handlers
